name: Windows-CRD1px

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run setup script
        shell: pwsh
        run: .github/workflows/setup.ps1
      - name: Starting CRD
        shell: pwsh
        run: |
          $authcode = "${{ github.event.inputs.authcode }}"
          $pincode = "${{ github.event.inputs.pincode }}"
          & $authcode -pin=$pincode
      - name: Keep Alive
        shell: pwsh
        run: ./timeout.ps1
